use crate::blocking;
use crate::error::AppError;
use crate::git::types::*;
use git2::{DiffOptions, Patch, Repository, Sort, Status, StatusOptions};
use std::path::Path;

const GITIGNORE_CONTENT: &str = r#"# BG3 Mod — auto-generated by CMTY Studio
# Packed mod archives
*.pak
*.zip

# loca should be comitted as xml, lsf should be comitted as lsx
*.loca
*.lsf

# Divine tool output
divine_output/

# OS files
Thumbs.db
.DS_Store

# Editor files
*.swp
*.swo
*~

# CMTY Studio local config (not shareable)
.cmtystudio/

# Build artifacts
__pycache__/
*.pyc
"#;

/// Build a `GitRepoInfo` from an opened `Repository`.
fn repo_to_info(repo: &Repository) -> Result<GitRepoInfo, String> {
    let head_branch = repo
        .head()
        .ok()
        .and_then(|r| r.shorthand().map(String::from));

    let head_oid = repo
        .head()
        .ok()
        .and_then(|r| r.target())
        .map(|o| o.to_string());

    let is_detached = repo.head_detached().unwrap_or(false);

    let has_remotes = repo.remotes().map(|r| !r.is_empty()).unwrap_or(false);

    let clean = repo.statuses(None).map(|s| s.is_empty()).unwrap_or(true);

    let (ahead, behind) = compute_ahead_behind(repo);

    let shallow = repo.is_shallow();
    let bare = repo.is_bare();
    let submodules = repo
        .submodules()
        .map(|subs| {
            subs.iter()
                .map(|s| s.path().to_string_lossy().into_owned())
                .collect()
        })
        .unwrap_or_default();

    Ok(GitRepoInfo {
        is_repo: true,
        head_branch,
        head_oid,
        is_detached,
        has_remotes,
        clean,
        ahead,
        behind,
        shallow,
        bare,
        submodules,
    })
}

/// Compute ahead/behind counts relative to the upstream tracking branch.
fn compute_ahead_behind(repo: &Repository) -> (u32, u32) {
    let head = match repo.head() {
        Ok(r) => r,
        Err(_) => return (0, 0),
    };
    let local_oid = match head.target() {
        Some(o) => o,
        None => return (0, 0),
    };
    let branch_name = match head.shorthand() {
        Some(n) => n.to_string(),
        None => return (0, 0),
    };
    let branch = match repo.find_branch(&branch_name, git2::BranchType::Local) {
        Ok(b) => b,
        Err(_) => return (0, 0),
    };
    let upstream = match branch.upstream() {
        Ok(u) => u,
        Err(_) => return (0, 0),
    };
    let upstream_oid = match upstream.get().target() {
        Some(o) => o,
        None => return (0, 0),
    };
    repo.graph_ahead_behind(local_oid, upstream_oid)
        .map(|(a, b)| (a as u32, b as u32))
        .unwrap_or((0, 0))
}

/// Map a `git2::Status` bitflag to a human-readable status string.
fn status_string(status: Status, staged: bool) -> &'static str {
    if staged {
        if status.intersects(Status::INDEX_NEW) {
            "added"
        } else if status.intersects(Status::INDEX_MODIFIED) {
            "modified"
        } else if status.intersects(Status::INDEX_DELETED) {
            "deleted"
        } else if status.intersects(Status::INDEX_RENAMED) {
            "renamed"
        } else {
            "modified"
        }
    } else if status.intersects(Status::WT_NEW) {
        "untracked"
    } else if status.intersects(Status::WT_MODIFIED) {
        "modified"
    } else if status.intersects(Status::WT_DELETED) {
        "deleted"
    } else if status.intersects(Status::WT_RENAMED) {
        "renamed"
    } else if status.intersects(Status::CONFLICTED) {
        "conflicted"
    } else {
        "modified"
    }
}

#[tauri::command]
pub async fn cmd_git_init(mod_path: String) -> Result<GitRepoInfo, AppError> {
    blocking(move || {
        let repo = Repository::init(&mod_path)
            .map_err(|e| format!("Failed to initialize git repo: {e}"))?;

        let gitignore_path = Path::new(&mod_path).join(".gitignore");
        std::fs::write(&gitignore_path, GITIGNORE_CONTENT)
            .map_err(|e| format!("Failed to write .gitignore: {e}"))?;

        repo_to_info(&repo)
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_clone(url: String, target_path: String) -> Result<GitRepoInfo, AppError> {
    blocking(move || {
        let mut callbacks = git2::RemoteCallbacks::new();
        callbacks.credentials(|url, username, allowed| {
            crate::git::credentials::https_credentials_callback(url, username, allowed)
        });

        let mut fetch_opts = git2::FetchOptions::new();
        fetch_opts.remote_callbacks(callbacks);

        let repo = git2::build::RepoBuilder::new()
            .fetch_options(fetch_opts)
            .clone(&url, Path::new(&target_path))
            .map_err(|e| format!("Failed to clone repository: {e}"))?;

        repo_to_info(&repo)
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_repo_info(mod_path: String) -> Result<Option<GitRepoInfo>, AppError> {
    blocking(move || match Repository::open(&mod_path) {
        Ok(repo) => repo_to_info(&repo).map(Some),
        Err(_) => Ok(None),
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_open(mod_path: String) -> Result<GitRepoInfo, AppError> {
    blocking(move || {
        let repo = Repository::open(&mod_path).map_err(|e| format!("Not a git repository: {e}"))?;
        repo_to_info(&repo)
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_status(mod_path: String) -> Result<Vec<GitFileStatus>, AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        let mut opts = StatusOptions::new();
        opts.include_untracked(true)
            .recurse_untracked_dirs(true)
            .include_unmodified(false);

        let statuses = repo
            .statuses(Some(&mut opts))
            .map_err(|e| format!("Failed to get status: {e}"))?;

        let mut result = Vec::new();

        for entry in statuses.iter() {
            let path = entry.path().unwrap_or("").to_string();
            let status = entry.status();

            let has_index_change = status.intersects(
                Status::INDEX_NEW
                    | Status::INDEX_MODIFIED
                    | Status::INDEX_DELETED
                    | Status::INDEX_RENAMED,
            );

            let has_wt_change = status.intersects(
                Status::WT_NEW
                    | Status::WT_MODIFIED
                    | Status::WT_DELETED
                    | Status::WT_RENAMED
                    | Status::CONFLICTED,
            );

            // A file can appear twice: once staged and once unstaged
            if has_index_change {
                let old_path = entry.head_to_index().and_then(|d| {
                    d.old_file()
                        .path()
                        .map(|p| p.to_string_lossy().into_owned())
                });
                result.push(GitFileStatus {
                    path: path.clone(),
                    status: status_string(status, true).to_string(),
                    staged: true,
                    old_path,
                });
            }

            if has_wt_change {
                let old_path = entry.index_to_workdir().and_then(|d| {
                    d.old_file()
                        .path()
                        .map(|p| p.to_string_lossy().into_owned())
                });
                result.push(GitFileStatus {
                    path: path.clone(),
                    status: status_string(status, false).to_string(),
                    staged: false,
                    old_path,
                });
            }
        }

        Ok(result)
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_stage(mod_path: String, paths: Vec<String>) -> Result<(), AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;
        let mut index = repo
            .index()
            .map_err(|e| format!("Failed to get index: {e}"))?;

        for p in &paths {
            index
                .add_path(Path::new(p))
                .map_err(|e| format!("Failed to stage '{p}': {e}"))?;
        }

        index
            .write()
            .map_err(|e| format!("Failed to write index: {e}"))?;
        Ok(())
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_stage_all(mod_path: String) -> Result<(), AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;
        let mut index = repo
            .index()
            .map_err(|e| format!("Failed to get index: {e}"))?;

        index
            .add_all(["*"], git2::IndexAddOption::DEFAULT, None)
            .map_err(|e| format!("Failed to stage all: {e}"))?;

        index
            .write()
            .map_err(|e| format!("Failed to write index: {e}"))?;
        Ok(())
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_unstage(mod_path: String, paths: Vec<String>) -> Result<(), AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        // Try to get HEAD commit — may not exist on brand-new repos
        match repo.head() {
            Ok(head_ref) => {
                let head_commit = head_ref
                    .peel_to_commit()
                    .map_err(|e| format!("Failed to peel HEAD to commit: {e}"))?;
                let path_refs: Vec<&Path> = paths.iter().map(|p| Path::new(p.as_str())).collect();
                repo.reset_default(Some(head_commit.as_object()), &path_refs)
                    .map_err(|e| format!("Failed to unstage: {e}"))?;
            }
            Err(_) => {
                // No HEAD yet (empty repo) — remove paths from index directly
                let mut index = repo
                    .index()
                    .map_err(|e| format!("Failed to get index: {e}"))?;
                for p in &paths {
                    index
                        .remove_path(Path::new(p))
                        .map_err(|e| format!("Failed to unstage '{p}': {e}"))?;
                }
                index
                    .write()
                    .map_err(|e| format!("Failed to write index: {e}"))?;
            }
        }

        Ok(())
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_discard(mod_path: String, paths: Vec<String>) -> Result<(), AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        let mut opts = StatusOptions::new();
        opts.include_untracked(true).recurse_untracked_dirs(true);
        let statuses = repo
            .statuses(Some(&mut opts))
            .map_err(|e| format!("Failed to get status: {e}"))?;

        // Classify paths into tracked (checkout from HEAD) vs untracked (delete)
        let mut tracked: Vec<String> = Vec::new();
        let mut untracked: Vec<String> = Vec::new();

        for p in &paths {
            let mut is_untracked = false;
            for entry in statuses.iter() {
                if entry.path() == Some(p.as_str()) && entry.status().intersects(Status::WT_NEW) {
                    is_untracked = true;
                    break;
                }
            }
            if is_untracked {
                untracked.push(p.clone());
            } else {
                tracked.push(p.clone());
            }
        }

        // Restore tracked files from HEAD
        if !tracked.is_empty() {
            let mut cb = git2::build::CheckoutBuilder::new();
            cb.force();
            for p in &tracked {
                cb.path(p);
            }
            repo.checkout_head(Some(&mut cb))
                .map_err(|e| format!("Failed to discard tracked changes: {e}"))?;
        }

        // Delete untracked files
        let root = Path::new(&mod_path);
        for p in &untracked {
            let full_path = root.join(p);
            if full_path.is_file() {
                std::fs::remove_file(&full_path)
                    .map_err(|e| format!("Failed to remove '{p}': {e}"))?;
            } else if full_path.is_dir() {
                std::fs::remove_dir_all(&full_path)
                    .map_err(|e| format!("Failed to remove directory '{p}': {e}"))?;
            }
        }

        Ok(())
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_diff_file(
    mod_path: String,
    path: String,
    staged: bool,
) -> Result<GitFileDiff, AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        let mut diff_opts = DiffOptions::new();
        diff_opts.pathspec(&path);

        let diff = if staged {
            // Diff index (staged) against HEAD tree
            let head_tree = repo.head().ok().and_then(|r| r.peel_to_tree().ok());
            repo.diff_tree_to_index(head_tree.as_ref(), None, Some(&mut diff_opts))
                .map_err(|e| format!("Failed to compute staged diff: {e}"))?
        } else {
            // Diff working dir against index
            repo.diff_index_to_workdir(None, Some(&mut diff_opts))
                .map_err(|e| format!("Failed to compute working dir diff: {e}"))?
        };

        let mut hunks: Vec<GitDiffHunk> = Vec::new();
        let mut is_binary = false;
        let mut old_size: Option<u64> = None;
        let mut new_size: Option<u64> = None;

        // Use Patch API to avoid borrow checker issues with diff.foreach
        for delta_idx in 0..diff.deltas().len() {
            let delta = diff.get_delta(delta_idx).expect("delta index in range");
            if delta.flags().is_binary() {
                is_binary = true;
            }
            old_size = Some(delta.old_file().size());
            new_size = Some(delta.new_file().size());

            if let Ok(Some(patch)) = Patch::from_diff(&diff, delta_idx) {
                for h in 0..patch.num_hunks() {
                    let (hunk, _num_lines) = patch
                        .hunk(h)
                        .map_err(|e| format!("Failed to get hunk: {e}"))?;
                    let mut lines = Vec::new();
                    for l in 0..patch
                        .num_lines_in_hunk(h)
                        .map_err(|e| format!("Failed to get line count: {e}"))?
                    {
                        let line = patch
                            .line_in_hunk(h, l)
                            .map_err(|e| format!("Failed to get line: {e}"))?;
                        let origin = match line.origin() {
                            '+' => "+",
                            '-' => "-",
                            _ => " ",
                        };
                        lines.push(GitDiffLine {
                            origin: origin.to_string(),
                            content: String::from_utf8_lossy(line.content()).to_string(),
                            old_lineno: line.old_lineno(),
                            new_lineno: line.new_lineno(),
                        });
                    }
                    hunks.push(GitDiffHunk {
                        header: String::from_utf8_lossy(hunk.header())
                            .trim_end()
                            .to_string(),
                        old_start: hunk.old_start(),
                        old_lines: hunk.old_lines(),
                        new_start: hunk.new_start(),
                        new_lines: hunk.new_lines(),
                        lines,
                    });
                }
            }
        }

        Ok(GitFileDiff {
            path,
            hunks,
            is_binary,
            old_size,
            new_size,
        })
    })
    .await
}

// ── Commit helpers ──────────────────────────────────────────────────

/// Build a `GitCommitInfo` from a `git2::Commit`.
fn commit_to_info(commit: &git2::Commit) -> GitCommitInfo {
    let oid = commit.id().to_string();
    GitCommitInfo {
        short_oid: oid[..7.min(oid.len())].to_string(),
        oid,
        message: commit.message().unwrap_or("").to_string(),
        author_name: commit.author().name().unwrap_or("").to_string(),
        author_email: commit.author().email().unwrap_or("").to_string(),
        timestamp: commit.time().seconds(),
        parent_count: commit.parent_count() as u32,
    }
}

// ── Commit commands ─────────────────────────────────────────────────

#[tauri::command]
pub async fn cmd_git_commit(mod_path: String, message: String) -> Result<GitCommitInfo, AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        let mut index = repo
            .index()
            .map_err(|e| format!("Failed to get index: {e}"))?;
        let tree_oid = index
            .write_tree()
            .map_err(|e| format!("Failed to write tree: {e}"))?;
        let tree = repo
            .find_tree(tree_oid)
            .map_err(|e| format!("Failed to find tree: {e}"))?;

        // Check if anything is staged (compare tree to HEAD tree)
        let head_tree = repo.head().ok().and_then(|r| r.peel_to_tree().ok());
        if let Some(ref ht) = head_tree {
            if ht.id() == tree_oid {
                return Err("Nothing to commit — stage changes first".to_string());
            }
        }

        let sig = crate::git::credentials::build_signature("", "")?;

        // Build parent list — empty for initial commit
        let parents: Vec<git2::Commit> = match repo.head() {
            Ok(head_ref) => {
                let commit = head_ref
                    .peel_to_commit()
                    .map_err(|e| format!("Failed to peel HEAD to commit: {e}"))?;
                vec![commit]
            }
            Err(_) => vec![],
        };
        let parent_refs: Vec<&git2::Commit> = parents.iter().collect();

        let commit_oid = repo
            .commit(Some("HEAD"), &sig, &sig, &message, &tree, &parent_refs)
            .map_err(|e| format!("Failed to create commit: {e}"))?;

        let commit = repo
            .find_commit(commit_oid)
            .map_err(|e| format!("Failed to find new commit: {e}"))?;

        Ok(commit_to_info(&commit))
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_amend(
    mod_path: String,
    message: Option<String>,
) -> Result<GitCommitInfo, AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        let head_ref = repo
            .head()
            .map_err(|e| format!("No HEAD commit to amend: {e}"))?;
        let head_commit = head_ref
            .peel_to_commit()
            .map_err(|e| format!("Failed to peel HEAD to commit: {e}"))?;

        let msg = message
            .as_deref()
            .unwrap_or_else(|| head_commit.message().unwrap_or(""));

        // Write index tree if there are staged changes, otherwise reuse HEAD tree
        let mut index = repo
            .index()
            .map_err(|e| format!("Failed to get index: {e}"))?;
        let tree_oid = index
            .write_tree()
            .map_err(|e| format!("Failed to write tree: {e}"))?;
        let tree = repo
            .find_tree(tree_oid)
            .map_err(|e| format!("Failed to find tree: {e}"))?;

        let amended_oid = head_commit
            .amend(Some("HEAD"), None, None, None, Some(msg), Some(&tree))
            .map_err(|e| format!("Failed to amend commit: {e}"))?;

        let amended_commit = repo
            .find_commit(amended_oid)
            .map_err(|e| format!("Failed to find amended commit: {e}"))?;

        Ok(commit_to_info(&amended_commit))
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_log(
    mod_path: String,
    limit: u32,
    offset: u32,
) -> Result<Vec<GitCommitInfo>, AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        // Handle repos with no commits yet
        let head = match repo.head() {
            Ok(r) => r,
            Err(_) => return Ok(Vec::new()),
        };
        let head_oid = match head.target() {
            Some(o) => o,
            None => return Ok(Vec::new()),
        };

        let mut revwalk = repo
            .revwalk()
            .map_err(|e| format!("Failed to create revwalk: {e}"))?;
        revwalk
            .push(head_oid)
            .map_err(|e| format!("Failed to push HEAD to revwalk: {e}"))?;
        revwalk
            .set_sorting(Sort::TIME)
            .map_err(|e| format!("Failed to set sorting: {e}"))?;

        let mut result = Vec::new();
        for (i, oid_result) in revwalk.enumerate() {
            if i < offset as usize {
                continue;
            }
            if result.len() >= limit as usize {
                break;
            }
            let oid = oid_result.map_err(|e| format!("Revwalk error: {e}"))?;
            let commit = repo
                .find_commit(oid)
                .map_err(|e| format!("Failed to find commit {oid}: {e}"))?;
            result.push(commit_to_info(&commit));
        }

        Ok(result)
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_show(
    mod_path: String,
    commit_oid: String,
) -> Result<GitCommitDetail, AppError> {
    blocking(move || {
        let repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        let oid = git2::Oid::from_str(&commit_oid)
            .map_err(|e| format!("Invalid OID '{commit_oid}': {e}"))?;
        let commit = repo
            .find_commit(oid)
            .map_err(|e| format!("Failed to find commit: {e}"))?;

        let commit_tree = commit
            .tree()
            .map_err(|e| format!("Failed to get commit tree: {e}"))?;

        // Get parent tree (or empty tree for initial commit)
        let parent_tree = if commit.parent_count() > 0 {
            Some(
                commit
                    .parent(0)
                    .map_err(|e| format!("Failed to get parent: {e}"))?
                    .tree()
                    .map_err(|e| format!("Failed to get parent tree: {e}"))?,
            )
        } else {
            None
        };

        let diff = repo
            .diff_tree_to_tree(parent_tree.as_ref(), Some(&commit_tree), None)
            .map_err(|e| format!("Failed to compute diff: {e}"))?;

        // Build file list from diff deltas
        let mut files = Vec::new();
        for delta in diff.deltas() {
            let path = delta
                .new_file()
                .path()
                .or_else(|| delta.old_file().path())
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_default();

            let status = match delta.status() {
                git2::Delta::Added => "added",
                git2::Delta::Deleted => "deleted",
                git2::Delta::Modified => "modified",
                git2::Delta::Renamed => "renamed",
                git2::Delta::Copied => "copied",
                _ => "modified",
            };

            let old_path = if delta.status() == git2::Delta::Renamed {
                delta
                    .old_file()
                    .path()
                    .map(|p| p.to_string_lossy().to_string())
            } else {
                None
            };

            files.push(GitFileStatus {
                path,
                status: status.to_string(),
                staged: true, // commit diffs are always "staged"
                old_path,
            });
        }

        // Build full diff with hunks using Patch API (avoids borrow checker issues with foreach)
        let mut diff_files: Vec<GitFileDiff> = Vec::new();

        for delta_idx in 0..diff.deltas().len() {
            let delta = diff.get_delta(delta_idx).expect("delta index in range");
            let file_path = delta
                .new_file()
                .path()
                .or_else(|| delta.old_file().path())
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_default();

            let mut file_hunks = Vec::new();

            if let Ok(Some(patch)) = Patch::from_diff(&diff, delta_idx) {
                for h in 0..patch.num_hunks() {
                    let (hunk, _) = patch
                        .hunk(h)
                        .map_err(|e| format!("Failed to get hunk: {e}"))?;
                    let mut lines = Vec::new();
                    for l in 0..patch
                        .num_lines_in_hunk(h)
                        .map_err(|e| format!("Failed to get line count: {e}"))?
                    {
                        let line = patch
                            .line_in_hunk(h, l)
                            .map_err(|e| format!("Failed to get line: {e}"))?;
                        let origin = match line.origin() {
                            '+' => "+",
                            '-' => "-",
                            _ => " ",
                        };
                        lines.push(GitDiffLine {
                            origin: origin.to_string(),
                            content: String::from_utf8_lossy(line.content()).to_string(),
                            old_lineno: line.old_lineno(),
                            new_lineno: line.new_lineno(),
                        });
                    }
                    file_hunks.push(GitDiffHunk {
                        header: String::from_utf8_lossy(hunk.header())
                            .trim_end()
                            .to_string(),
                        old_start: hunk.old_start(),
                        old_lines: hunk.old_lines(),
                        new_start: hunk.new_start(),
                        new_lines: hunk.new_lines(),
                        lines,
                    });
                }
            }

            diff_files.push(GitFileDiff {
                path: file_path,
                hunks: file_hunks,
                is_binary: delta.flags().is_binary(),
                old_size: Some(delta.old_file().size()),
                new_size: Some(delta.new_file().size()),
            });
        }

        Ok(GitCommitDetail {
            commit: commit_to_info(&commit),
            files,
            diff: diff_files,
        })
    })
    .await
}

// ── Stash commands ──────────────────────────────────────────────────

#[tauri::command]
pub async fn cmd_git_stash(mod_path: String, message: Option<String>) -> Result<(), AppError> {
    blocking(move || {
        let mut repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        let sig = crate::git::credentials::build_signature("", "")?;

        repo.stash_save(&sig, message.as_deref().unwrap_or("WIP"), None)
            .map_err(|e| format!("Failed to stash changes: {e}"))?;

        Ok(())
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_stash_list(mod_path: String) -> Result<Vec<GitStashEntry>, AppError> {
    blocking(move || {
        let mut repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        let mut entries = Vec::new();
        repo.stash_foreach(|index, message, oid| {
            entries.push(GitStashEntry {
                index: index as u32,
                message: message.to_string(),
                oid: oid.to_string(),
            });
            true
        })
        .map_err(|e| format!("Failed to list stashes: {e}"))?;

        Ok(entries)
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_stash_apply(mod_path: String, index: u32) -> Result<(), AppError> {
    blocking(move || {
        let mut repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        repo.stash_apply(index as usize, None)
            .map_err(|e| format!("Failed to apply stash @{{{index}}}: {e}"))?;

        Ok(())
    })
    .await
}

#[tauri::command]
pub async fn cmd_git_stash_drop(mod_path: String, index: u32) -> Result<(), AppError> {
    blocking(move || {
        let mut repo =
            Repository::open(&mod_path).map_err(|e| format!("Failed to open repository: {e}"))?;

        repo.stash_drop(index as usize)
            .map_err(|e| format!("Failed to drop stash @{{{index}}}: {e}"))?;

        Ok(())
    })
    .await
}
